### ISSUE TITLE
Dynamic Streaming of multiple user timeline (id sets)

### ISSUE THREAD

**Issue by Isty001** [impensavel/floodgate#1]
Hi,

I'm using your Twitter Stream Api PHP library, and it's working great with hard coded data. But I want to make it dynamic. When a user logs in, pass the list of ids he/she is following, and start streaming it. It'd be great if I could achieve it one process. But when the streaming starts, the parameters can't be changed during that.

Could you give me some help with it?

Thanks in advance.

**Comment by quetzyg** [comment]
Hi there,

I'm about to release a new version and updated documentation. If you bear with me, you won't be disappointed ;)

**Comment by Isty001** [comment]
Great! Thank you! And will it be easily possible to do what I want to? : )

**Comment by quetzyg** [comment]
Yup!

**Comment by Isty001** [comment]
Nice, can't wait for it. :P

**Comment by quetzyg** [comment]
The answer to your question can be seen [here](https://github.com/impensavel/floodgate/blob/master/docs/Floodgate.md#example-2).

**Comment by Isty001** [comment]
Thank you, I'll check as soon as I can!

**Comment by Isty001** [comment]
Thank you, I like the new way of configuration, but unfortunately I couldn't figure out the actual solution I needed. If I'm correct the generator will keep getting the new data from  the 'Keyword' class' method (just to stick to the example), right? 

And my other problem is the 'elapsed time from the last (re)connection must be at least 300 seconds' So it will start reading based on new parameters only after 5 minutes?

I'm lost in this a bit sorry. :D What I want to achieve is that a user logs in -> start stream their timeline immediately, when logs out, stop it. If possible with one process.

**Comment by quetzyg** [comment]
Hi,

Yes, the parameter generator will be executed every 300 seconds (by default). The value in itself isn't mandatory, it's just a sane value that _should_ be used, but you can lower it if needed by passing the following configuration when creating a `Floodgate` instance:
```php
$config = [
    'floodgate' => [
        'reconnection_delay' => 60,
    ],
    'oauth' => [
        // ...
    ],
];
```

This however, isn't a good idea, so keep that in mind since it might trigger the API rate limits quickly!

Also bear in mind that this library should be used in a standalone script, either for manual execution (command line) or via cronjob.

**Comment by Isty001** [comment]
Yeah, I saw that in your docs, just thought that maybe it's possible to hack it somehow. :D 
Maybe it's not what I'm looking for, or not even possible, but thanks for you help anyway!

**Comment by quetzyg** [comment]
For your needs, it's probably easier to use the REST API instead of the Streaming API.

**Comment by Isty001** [comment]
Maybe not if I can start a session for each user. Is it possible to setup a user stream (https://dev.twitter.com/streaming/userstreams) specially a timeline of the user with this library? And the other thing, is it possible to stop the stream somehow?

**Comment by quetzyg** [comment]
The library doesn't support User streams out of the box, but it's easy if you extend the class and implement the User stream consumer method and change the URL. I'll probably add it soon.

**Comment by Isty001** [comment]
Great, thanks for the tip. The last thing I want to know, is what if I execute several commands to start different streams but inside a daemon process, so I can't actually see the stream processes, but I need to stop them at a point somehow. Could you recommend a solution for this?

**Comment by quetzyg** [comment]
You would have to execute each User stream in it's own instance (same script with different parameters/credentials), because a connection has to be made and left open for consumption.

The consumption loop will be running in an infinite loop, so to stop it you'll have to trigger an `Exception` in the generator.

**Comment by quetzyg** [comment]
Given this isn't about an issue with the library itself, but rather an implementation question, I'm gonna close this issue. You should use StackOverflow for these types of questions, not the issue tracker.
